apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: uf44v5pvh-nodejs 
  janus-idp.io/tekton: uf44v5pvh-nodejs
  backstage.io/kubernetes-id: uf44v5pvh-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uf44v5pvh-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml