apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uf44v5pvh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uf44v5pvh-nodejs 
  name: uf44v5pvh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uf44v5pvh-nodejs 
